disabled_rules:
  - trailing_whitespace
  - force_try
included:
excluded:
  - Sources
  - Packages

force_cast: warning
line_length: 200
file_length:
  warning: 400
  error: 1000
type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
identifier_name:
  min_length:
    error: 4
  excluded:
    - id
    - URL