os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
services:
  - redis-server
install:
  - eval "$(curl -sL https://apt.vapor.sh)"
  - eval "$(curl -sL https://ci.restrt.tech/travis_mysql)"
  - eval "$(curl -sL https://swift.vapor.sh/codecov)"
